/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
    UserRoleEnumToJSONTyped,
} from './UserRoleEnum';

/**
 * 
 * @export
 * @interface AddMemberRequest
 */
export interface AddMemberRequest {
    /**
     * 
     * @type {string}
     * @memberof AddMemberRequest
     */
    userId: string;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof AddMemberRequest
     */
    role: UserRoleEnum;
}



/**
 * Check if a given object implements the AddMemberRequest interface.
 */
export function instanceOfAddMemberRequest(value: object): value is AddMemberRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function AddMemberRequestFromJSON(json: any): AddMemberRequest {
    return AddMemberRequestFromJSONTyped(json, false);
}

export function AddMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'role': UserRoleEnumFromJSON(json['role']),
    };
}

export function AddMemberRequestToJSON(json: any): AddMemberRequest {
    return AddMemberRequestToJSONTyped(json, false);
}

export function AddMemberRequestToJSONTyped(value?: AddMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'role': UserRoleEnumToJSON(value['role']),
    };
}

