/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationAddRecord
 */
export interface ApplicationAddRecord {
    /**
     * 
     * @type {string}
     * @memberof ApplicationAddRecord
     */
    coverLetter?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApplicationAddRecord
     */
    expectedSalary?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationAddRecord
     */
    jobPostId: string;
}

/**
 * Check if a given object implements the ApplicationAddRecord interface.
 */
export function instanceOfApplicationAddRecord(value: object): value is ApplicationAddRecord {
    if (!('jobPostId' in value) || value['jobPostId'] === undefined) return false;
    return true;
}

export function ApplicationAddRecordFromJSON(json: any): ApplicationAddRecord {
    return ApplicationAddRecordFromJSONTyped(json, false);
}

export function ApplicationAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'coverLetter': json['coverLetter'] == null ? undefined : json['coverLetter'],
        'expectedSalary': json['expectedSalary'] == null ? undefined : json['expectedSalary'],
        'jobPostId': json['jobPostId'],
    };
}

export function ApplicationAddRecordToJSON(json: any): ApplicationAddRecord {
    return ApplicationAddRecordToJSONTyped(json, false);
}

export function ApplicationAddRecordToJSONTyped(value?: ApplicationAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coverLetter': value['coverLetter'],
        'expectedSalary': value['expectedSalary'],
        'jobPostId': value['jobPostId'],
    };
}

