/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRecord } from './UserRecord';
import {
    UserRecordFromJSON,
    UserRecordFromJSONTyped,
    UserRecordToJSON,
    UserRecordToJSONTyped,
} from './UserRecord';
import type { JobPostRecord } from './JobPostRecord';
import {
    JobPostRecordFromJSON,
    JobPostRecordFromJSONTyped,
    JobPostRecordToJSON,
    JobPostRecordToJSONTyped,
} from './JobPostRecord';
import type { ApplicationStatusEnum } from './ApplicationStatusEnum';
import {
    ApplicationStatusEnumFromJSON,
    ApplicationStatusEnumFromJSONTyped,
    ApplicationStatusEnumToJSON,
    ApplicationStatusEnumToJSONTyped,
} from './ApplicationStatusEnum';

/**
 * 
 * @export
 * @interface ApplicationRecord
 */
export interface ApplicationRecord {
    /**
     * 
     * @type {string}
     * @memberof ApplicationRecord
     */
    id: string;
    /**
     * 
     * @type {ApplicationStatusEnum}
     * @memberof ApplicationRecord
     */
    status: ApplicationStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRecord
     */
    coverLetter?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApplicationRecord
     */
    expectedSalary?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRecord
     */
    userId: string;
    /**
     * 
     * @type {UserRecord}
     * @memberof ApplicationRecord
     */
    user?: UserRecord | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRecord
     */
    jobPostId: string;
    /**
     * 
     * @type {JobPostRecord}
     * @memberof ApplicationRecord
     */
    jobPost?: JobPostRecord | null;
}



/**
 * Check if a given object implements the ApplicationRecord interface.
 */
export function instanceOfApplicationRecord(value: object): value is ApplicationRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('jobPostId' in value) || value['jobPostId'] === undefined) return false;
    return true;
}

export function ApplicationRecordFromJSON(json: any): ApplicationRecord {
    return ApplicationRecordFromJSONTyped(json, false);
}

export function ApplicationRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': ApplicationStatusEnumFromJSON(json['status']),
        'coverLetter': json['coverLetter'] == null ? undefined : json['coverLetter'],
        'expectedSalary': json['expectedSalary'] == null ? undefined : json['expectedSalary'],
        'userId': json['userId'],
        'user': json['user'] == null ? undefined : UserRecordFromJSON(json['user']),
        'jobPostId': json['jobPostId'],
        'jobPost': json['jobPost'] == null ? undefined : JobPostRecordFromJSON(json['jobPost']),
    };
}

export function ApplicationRecordToJSON(json: any): ApplicationRecord {
    return ApplicationRecordToJSONTyped(json, false);
}

export function ApplicationRecordToJSONTyped(value?: ApplicationRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': ApplicationStatusEnumToJSON(value['status']),
        'coverLetter': value['coverLetter'],
        'expectedSalary': value['expectedSalary'],
        'userId': value['userId'],
        'user': UserRecordToJSON(value['user']),
        'jobPostId': value['jobPostId'],
        'jobPost': JobPostRecordToJSON(value['jobPost']),
    };
}

