/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplicationStatusEnum } from './ApplicationStatusEnum';
import {
    ApplicationStatusEnumFromJSON,
    ApplicationStatusEnumFromJSONTyped,
    ApplicationStatusEnumToJSON,
    ApplicationStatusEnumToJSONTyped,
} from './ApplicationStatusEnum';

/**
 * 
 * @export
 * @interface ApplicationUpdateRecord
 */
export interface ApplicationUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof ApplicationUpdateRecord
     */
    id: string;
    /**
     * 
     * @type {ApplicationStatusEnum}
     * @memberof ApplicationUpdateRecord
     */
    status?: ApplicationStatusEnum | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUpdateRecord
     */
    coverLetter?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApplicationUpdateRecord
     */
    expectedSalary?: number | null;
}



/**
 * Check if a given object implements the ApplicationUpdateRecord interface.
 */
export function instanceOfApplicationUpdateRecord(value: object): value is ApplicationUpdateRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ApplicationUpdateRecordFromJSON(json: any): ApplicationUpdateRecord {
    return ApplicationUpdateRecordFromJSONTyped(json, false);
}

export function ApplicationUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'] == null ? undefined : ApplicationStatusEnumFromJSON(json['status']),
        'coverLetter': json['coverLetter'] == null ? undefined : json['coverLetter'],
        'expectedSalary': json['expectedSalary'] == null ? undefined : json['expectedSalary'],
    };
}

export function ApplicationUpdateRecordToJSON(json: any): ApplicationUpdateRecord {
    return ApplicationUpdateRecordToJSONTyped(json, false);
}

export function ApplicationUpdateRecordToJSONTyped(value?: ApplicationUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': ApplicationStatusEnumToJSON(value['status']),
        'coverLetter': value['coverLetter'],
        'expectedSalary': value['expectedSalary'],
    };
}

