/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';
import type { ApplicationRecord } from './ApplicationRecord';
import {
    ApplicationRecordFromJSON,
    ApplicationRecordFromJSONTyped,
    ApplicationRecordToJSON,
    ApplicationRecordToJSONTyped,
} from './ApplicationRecord';

/**
 * 
 * @export
 * @interface ApplicationRecordListRequestResponse
 */
export interface ApplicationRecordListRequestResponse {
    /**
     * 
     * @type {Array<ApplicationRecord>}
     * @memberof ApplicationRecordListRequestResponse
     */
    readonly response?: Array<ApplicationRecord> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ApplicationRecordListRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the ApplicationRecordListRequestResponse interface.
 */
export function instanceOfApplicationRecordListRequestResponse(value: object): value is ApplicationRecordListRequestResponse {
    return true;
}

export function ApplicationRecordListRequestResponseFromJSON(json: any): ApplicationRecordListRequestResponse {
    return ApplicationRecordListRequestResponseFromJSONTyped(json, false);
}

export function ApplicationRecordListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationRecordListRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ((json['response'] as Array<any>).map(ApplicationRecordFromJSON)),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ApplicationRecordListRequestResponseToJSON(json: any): ApplicationRecordListRequestResponse {
    return ApplicationRecordListRequestResponseToJSONTyped(json, false);
}

export function ApplicationRecordListRequestResponseToJSONTyped(value?: Omit<ApplicationRecordListRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

