/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyRecord } from './CompanyRecord';
import {
    CompanyRecordFromJSON,
    CompanyRecordFromJSONTyped,
    CompanyRecordToJSON,
    CompanyRecordToJSONTyped,
} from './CompanyRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CompanyRecordRequestResponse
 */
export interface CompanyRecordRequestResponse {
    /**
     * 
     * @type {CompanyRecord}
     * @memberof CompanyRecordRequestResponse
     */
    readonly response?: CompanyRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CompanyRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the CompanyRecordRequestResponse interface.
 */
export function instanceOfCompanyRecordRequestResponse(value: object): value is CompanyRecordRequestResponse {
    return true;
}

export function CompanyRecordRequestResponseFromJSON(json: any): CompanyRecordRequestResponse {
    return CompanyRecordRequestResponseFromJSONTyped(json, false);
}

export function CompanyRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : CompanyRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CompanyRecordRequestResponseToJSON(json: any): CompanyRecordRequestResponse {
    return CompanyRecordRequestResponseToJSONTyped(json, false);
}

export function CompanyRecordRequestResponseToJSONTyped(value?: Omit<CompanyRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

