/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyRecord
 */
export interface CompanyRecord {
    /**
     * 
     * @type {string}
     * @memberof CompanyRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyRecord
     */
    industry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyRecord
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyRecord
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CompanyRecord interface.
 */
export function instanceOfCompanyRecord(value: object): value is CompanyRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CompanyRecordFromJSON(json: any): CompanyRecord {
    return CompanyRecordFromJSONTyped(json, false);
}

export function CompanyRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'website': json['website'] == null ? undefined : json['website'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CompanyRecordToJSON(json: any): CompanyRecord {
    return CompanyRecordToJSONTyped(json, false);
}

export function CompanyRecordToJSONTyped(value?: CompanyRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'industry': value['industry'],
        'website': value['website'],
        'description': value['description'],
    };
}

