/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRecord } from './UserRecord';
import {
    UserRecordFromJSON,
    UserRecordFromJSONTyped,
    UserRecordToJSON,
    UserRecordToJSONTyped,
} from './UserRecord';

/**
 * 
 * @export
 * @interface CompanyMemberRecord
 */
export interface CompanyMemberRecord {
    /**
     * 
     * @type {string}
     * @memberof CompanyMemberRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyMemberRecord
     */
    userId: string;
    /**
     * 
     * @type {UserRecord}
     * @memberof CompanyMemberRecord
     */
    user?: UserRecord | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyMemberRecord
     */
    companyId: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyMemberRecord
     */
    role: string;
}

/**
 * Check if a given object implements the CompanyMemberRecord interface.
 */
export function instanceOfCompanyMemberRecord(value: object): value is CompanyMemberRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function CompanyMemberRecordFromJSON(json: any): CompanyMemberRecord {
    return CompanyMemberRecordFromJSONTyped(json, false);
}

export function CompanyMemberRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyMemberRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'user': json['user'] == null ? undefined : UserRecordFromJSON(json['user']),
        'companyId': json['companyId'],
        'role': json['role'],
    };
}

export function CompanyMemberRecordToJSON(json: any): CompanyMemberRecord {
    return CompanyMemberRecordToJSONTyped(json, false);
}

export function CompanyMemberRecordToJSONTyped(value?: CompanyMemberRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'user': UserRecordToJSON(value['user']),
        'companyId': value['companyId'],
        'role': value['role'],
    };
}

