/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyUpdateRecord
 */
export interface CompanyUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof CompanyUpdateRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyUpdateRecord
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyUpdateRecord
     */
    industry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyUpdateRecord
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyUpdateRecord
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CompanyUpdateRecord interface.
 */
export function instanceOfCompanyUpdateRecord(value: object): value is CompanyUpdateRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CompanyUpdateRecordFromJSON(json: any): CompanyUpdateRecord {
    return CompanyUpdateRecordFromJSONTyped(json, false);
}

export function CompanyUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'website': json['website'] == null ? undefined : json['website'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CompanyUpdateRecordToJSON(json: any): CompanyUpdateRecord {
    return CompanyUpdateRecordToJSONTyped(json, false);
}

export function CompanyUpdateRecordToJSONTyped(value?: CompanyUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'industry': value['industry'],
        'website': value['website'],
        'description': value['description'],
    };
}

