/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyMemberRecord } from './CompanyMemberRecord';
import {
    CompanyMemberRecordFromJSON,
    CompanyMemberRecordFromJSONTyped,
    CompanyMemberRecordToJSON,
    CompanyMemberRecordToJSONTyped,
} from './CompanyMemberRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CompanyMemberRecordListRequestResponse
 */
export interface CompanyMemberRecordListRequestResponse {
    /**
     * 
     * @type {Array<CompanyMemberRecord>}
     * @memberof CompanyMemberRecordListRequestResponse
     */
    readonly response?: Array<CompanyMemberRecord> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CompanyMemberRecordListRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the CompanyMemberRecordListRequestResponse interface.
 */
export function instanceOfCompanyMemberRecordListRequestResponse(value: object): value is CompanyMemberRecordListRequestResponse {
    return true;
}

export function CompanyMemberRecordListRequestResponseFromJSON(json: any): CompanyMemberRecordListRequestResponse {
    return CompanyMemberRecordListRequestResponseFromJSONTyped(json, false);
}

export function CompanyMemberRecordListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyMemberRecordListRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ((json['response'] as Array<any>).map(CompanyMemberRecordFromJSON)),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CompanyMemberRecordListRequestResponseToJSON(json: any): CompanyMemberRecordListRequestResponse {
    return CompanyMemberRecordListRequestResponseToJSONTyped(json, false);
}

export function CompanyMemberRecordListRequestResponseToJSONTyped(value?: Omit<CompanyMemberRecordListRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

