/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyAddRecord
 */
export interface CompanyAddRecord {
    /**
     * 
     * @type {string}
     * @memberof CompanyAddRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyAddRecord
     */
    industry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyAddRecord
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyAddRecord
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CompanyAddRecord interface.
 */
export function instanceOfCompanyAddRecord(value: object): value is CompanyAddRecord {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CompanyAddRecordFromJSON(json: any): CompanyAddRecord {
    return CompanyAddRecordFromJSONTyped(json, false);
}

export function CompanyAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'website': json['website'] == null ? undefined : json['website'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CompanyAddRecordToJSON(json: any): CompanyAddRecord {
    return CompanyAddRecordToJSONTyped(json, false);
}

export function CompanyAddRecordToJSONTyped(value?: CompanyAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'industry': value['industry'],
        'website': value['website'],
        'description': value['description'],
    };
}

