/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyRecord } from './CompanyRecord';
import {
    CompanyRecordFromJSON,
    CompanyRecordFromJSONTyped,
    CompanyRecordToJSON,
    CompanyRecordToJSONTyped,
} from './CompanyRecord';

/**
 * 
 * @export
 * @interface JobPostRecord
 */
export interface JobPostRecord {
    /**
     * 
     * @type {string}
     * @memberof JobPostRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof JobPostRecord
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof JobPostRecord
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostRecord
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostRecord
     */
    salaryRange?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostRecord
     */
    level?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostRecord
     */
    type?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobPostRecord
     */
    isRecruiterPosition: boolean;
    /**
     * 
     * @type {CompanyRecord}
     * @memberof JobPostRecord
     */
    company?: CompanyRecord | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostRecord
     */
    companyId: string;
}

/**
 * Check if a given object implements the JobPostRecord interface.
 */
export function instanceOfJobPostRecord(value: object): value is JobPostRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('isRecruiterPosition' in value) || value['isRecruiterPosition'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    return true;
}

export function JobPostRecordFromJSON(json: any): JobPostRecord {
    return JobPostRecordFromJSONTyped(json, false);
}

export function JobPostRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobPostRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : json['location'],
        'salaryRange': json['salaryRange'] == null ? undefined : json['salaryRange'],
        'level': json['level'] == null ? undefined : json['level'],
        'type': json['type'] == null ? undefined : json['type'],
        'isRecruiterPosition': json['isRecruiterPosition'],
        'company': json['company'] == null ? undefined : CompanyRecordFromJSON(json['company']),
        'companyId': json['companyId'],
    };
}

export function JobPostRecordToJSON(json: any): JobPostRecord {
    return JobPostRecordToJSONTyped(json, false);
}

export function JobPostRecordToJSONTyped(value?: JobPostRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'location': value['location'],
        'salaryRange': value['salaryRange'],
        'level': value['level'],
        'type': value['type'],
        'isRecruiterPosition': value['isRecruiterPosition'],
        'company': CompanyRecordToJSON(value['company']),
        'companyId': value['companyId'],
    };
}

