/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobPostUpdateRecord
 */
export interface JobPostUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof JobPostUpdateRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof JobPostUpdateRecord
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostUpdateRecord
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostUpdateRecord
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostUpdateRecord
     */
    salaryRange?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostUpdateRecord
     */
    level?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostUpdateRecord
     */
    type?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobPostUpdateRecord
     */
    isRecruiterPosition?: boolean | null;
}

/**
 * Check if a given object implements the JobPostUpdateRecord interface.
 */
export function instanceOfJobPostUpdateRecord(value: object): value is JobPostUpdateRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function JobPostUpdateRecordFromJSON(json: any): JobPostUpdateRecord {
    return JobPostUpdateRecordFromJSONTyped(json, false);
}

export function JobPostUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobPostUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : json['location'],
        'salaryRange': json['salaryRange'] == null ? undefined : json['salaryRange'],
        'level': json['level'] == null ? undefined : json['level'],
        'type': json['type'] == null ? undefined : json['type'],
        'isRecruiterPosition': json['isRecruiterPosition'] == null ? undefined : json['isRecruiterPosition'],
    };
}

export function JobPostUpdateRecordToJSON(json: any): JobPostUpdateRecord {
    return JobPostUpdateRecordToJSONTyped(json, false);
}

export function JobPostUpdateRecordToJSONTyped(value?: JobPostUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'location': value['location'],
        'salaryRange': value['salaryRange'],
        'level': value['level'],
        'type': value['type'],
        'isRecruiterPosition': value['isRecruiterPosition'],
    };
}

