/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobPostAddRecord
 */
export interface JobPostAddRecord {
    /**
     * 
     * @type {string}
     * @memberof JobPostAddRecord
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof JobPostAddRecord
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostAddRecord
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostAddRecord
     */
    salaryRange?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostAddRecord
     */
    level?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostAddRecord
     */
    type?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobPostAddRecord
     */
    isRecruiterPosition: boolean;
    /**
     * 
     * @type {string}
     * @memberof JobPostAddRecord
     */
    companyId: string;
}

/**
 * Check if a given object implements the JobPostAddRecord interface.
 */
export function instanceOfJobPostAddRecord(value: object): value is JobPostAddRecord {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('isRecruiterPosition' in value) || value['isRecruiterPosition'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    return true;
}

export function JobPostAddRecordFromJSON(json: any): JobPostAddRecord {
    return JobPostAddRecordFromJSONTyped(json, false);
}

export function JobPostAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobPostAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : json['location'],
        'salaryRange': json['salaryRange'] == null ? undefined : json['salaryRange'],
        'level': json['level'] == null ? undefined : json['level'],
        'type': json['type'] == null ? undefined : json['type'],
        'isRecruiterPosition': json['isRecruiterPosition'],
        'companyId': json['companyId'],
    };
}

export function JobPostAddRecordToJSON(json: any): JobPostAddRecord {
    return JobPostAddRecordToJSONTyped(json, false);
}

export function JobPostAddRecordToJSONTyped(value?: JobPostAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'location': value['location'],
        'salaryRange': value['salaryRange'],
        'level': value['level'],
        'type': value['type'],
        'isRecruiterPosition': value['isRecruiterPosition'],
        'companyId': value['companyId'],
    };
}

