/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobPostRecord } from './JobPostRecord';
import {
    JobPostRecordFromJSON,
    JobPostRecordFromJSONTyped,
    JobPostRecordToJSON,
    JobPostRecordToJSONTyped,
} from './JobPostRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface JobPostRecordListRequestResponse
 */
export interface JobPostRecordListRequestResponse {
    /**
     * 
     * @type {Array<JobPostRecord>}
     * @memberof JobPostRecordListRequestResponse
     */
    readonly response?: Array<JobPostRecord> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof JobPostRecordListRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the JobPostRecordListRequestResponse interface.
 */
export function instanceOfJobPostRecordListRequestResponse(value: object): value is JobPostRecordListRequestResponse {
    return true;
}

export function JobPostRecordListRequestResponseFromJSON(json: any): JobPostRecordListRequestResponse {
    return JobPostRecordListRequestResponseFromJSONTyped(json, false);
}

export function JobPostRecordListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobPostRecordListRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ((json['response'] as Array<any>).map(JobPostRecordFromJSON)),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function JobPostRecordListRequestResponseToJSON(json: any): JobPostRecordListRequestResponse {
    return JobPostRecordListRequestResponseToJSONTyped(json, false);
}

export function JobPostRecordListRequestResponseToJSONTyped(value?: Omit<JobPostRecordListRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

