/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobPostRecord } from './JobPostRecord';
import {
    JobPostRecordFromJSON,
    JobPostRecordFromJSONTyped,
    JobPostRecordToJSON,
    JobPostRecordToJSONTyped,
} from './JobPostRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface JobPostRecordRequestResponse
 */
export interface JobPostRecordRequestResponse {
    /**
     * 
     * @type {JobPostRecord}
     * @memberof JobPostRecordRequestResponse
     */
    readonly response?: JobPostRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof JobPostRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the JobPostRecordRequestResponse interface.
 */
export function instanceOfJobPostRecordRequestResponse(value: object): value is JobPostRecordRequestResponse {
    return true;
}

export function JobPostRecordRequestResponseFromJSON(json: any): JobPostRecordRequestResponse {
    return JobPostRecordRequestResponseFromJSONTyped(json, false);
}

export function JobPostRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobPostRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : JobPostRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function JobPostRecordRequestResponseToJSON(json: any): JobPostRecordRequestResponse {
    return JobPostRecordRequestResponseToJSONTyped(json, false);
}

export function JobPostRecordRequestResponseToJSONTyped(value?: Omit<JobPostRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

