/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileUpdateRecord
 */
export interface UserProfileUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateRecord
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateRecord
     */
    profilePictureUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateRecord
     */
    linkedInUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateRecord
     */
    gitHubUrl?: string | null;
}

/**
 * Check if a given object implements the UserProfileUpdateRecord interface.
 */
export function instanceOfUserProfileUpdateRecord(value: object): value is UserProfileUpdateRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UserProfileUpdateRecordFromJSON(json: any): UserProfileUpdateRecord {
    return UserProfileUpdateRecordFromJSONTyped(json, false);
}

export function UserProfileUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'profilePictureUrl': json['profilePictureUrl'] == null ? undefined : json['profilePictureUrl'],
        'linkedInUrl': json['linkedInUrl'] == null ? undefined : json['linkedInUrl'],
        'gitHubUrl': json['gitHubUrl'] == null ? undefined : json['gitHubUrl'],
    };
}

export function UserProfileUpdateRecordToJSON(json: any): UserProfileUpdateRecord {
    return UserProfileUpdateRecordToJSONTyped(json, false);
}

export function UserProfileUpdateRecordToJSONTyped(value?: UserProfileUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bio': value['bio'],
        'profilePictureUrl': value['profilePictureUrl'],
        'linkedInUrl': value['linkedInUrl'],
        'gitHubUrl': value['gitHubUrl'],
    };
}

