/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileRecord
 */
export interface UserProfileRecord {
    /**
     * 
     * @type {string}
     * @memberof UserProfileRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileRecord
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileRecord
     */
    profilePictureUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileRecord
     */
    linkedInUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileRecord
     */
    gitHubUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileRecord
     */
    userId: string;
}

/**
 * Check if a given object implements the UserProfileRecord interface.
 */
export function instanceOfUserProfileRecord(value: object): value is UserProfileRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UserProfileRecordFromJSON(json: any): UserProfileRecord {
    return UserProfileRecordFromJSONTyped(json, false);
}

export function UserProfileRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'profilePictureUrl': json['profilePictureUrl'] == null ? undefined : json['profilePictureUrl'],
        'linkedInUrl': json['linkedInUrl'] == null ? undefined : json['linkedInUrl'],
        'gitHubUrl': json['gitHubUrl'] == null ? undefined : json['gitHubUrl'],
        'userId': json['userId'],
    };
}

export function UserProfileRecordToJSON(json: any): UserProfileRecord {
    return UserProfileRecordToJSONTyped(json, false);
}

export function UserProfileRecordToJSONTyped(value?: UserProfileRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bio': value['bio'],
        'profilePictureUrl': value['profilePictureUrl'],
        'linkedInUrl': value['linkedInUrl'],
        'gitHubUrl': value['gitHubUrl'],
        'userId': value['userId'],
    };
}

