/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfileRecord } from './UserProfileRecord';
import {
    UserProfileRecordFromJSON,
    UserProfileRecordFromJSONTyped,
    UserProfileRecordToJSON,
    UserProfileRecordToJSONTyped,
} from './UserProfileRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface UserProfileRecordRequestResponse
 */
export interface UserProfileRecordRequestResponse {
    /**
     * 
     * @type {UserProfileRecord}
     * @memberof UserProfileRecordRequestResponse
     */
    readonly response?: UserProfileRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof UserProfileRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the UserProfileRecordRequestResponse interface.
 */
export function instanceOfUserProfileRecordRequestResponse(value: object): value is UserProfileRecordRequestResponse {
    return true;
}

export function UserProfileRecordRequestResponseFromJSON(json: any): UserProfileRecordRequestResponse {
    return UserProfileRecordRequestResponseFromJSONTyped(json, false);
}

export function UserProfileRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : UserProfileRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function UserProfileRecordRequestResponseToJSON(json: any): UserProfileRecordRequestResponse {
    return UserProfileRecordRequestResponseToJSONTyped(json, false);
}

export function UserProfileRecordRequestResponseToJSONTyped(value?: Omit<UserProfileRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

