/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApplicationAddRecord,
  ApplicationRecordListRequestResponse,
  ApplicationUpdateRecord,
  RequestResponse,
} from '../models/index';
import {
    ApplicationAddRecordFromJSON,
    ApplicationAddRecordToJSON,
    ApplicationRecordListRequestResponseFromJSON,
    ApplicationRecordListRequestResponseToJSON,
    ApplicationUpdateRecordFromJSON,
    ApplicationUpdateRecordToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models/index';

export interface ApiApplicationApplyPostRequest {
    applicationAddRecord?: ApplicationAddRecord;
}

export interface ApiApplicationGetJobApplicationsJobPostIdGetRequest {
    jobPostId: string;
}

export interface ApiApplicationUpdateStatusPutRequest {
    applicationUpdateRecord?: ApplicationUpdateRecord;
}

/**
 * 
 */
export class ApplicationApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiApplicationApplyPost without sending the request
     */
    async apiApplicationApplyPostRequestOpts(requestParameters: ApiApplicationApplyPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Application/Apply`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApplicationAddRecordToJSON(requestParameters['applicationAddRecord']),
        };
    }

    /**
     */
    async apiApplicationApplyPostRaw(requestParameters: ApiApplicationApplyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiApplicationApplyPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiApplicationApplyPost(requestParameters: ApiApplicationApplyPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiApplicationApplyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiApplicationGetJobApplicationsJobPostIdGet without sending the request
     */
    async apiApplicationGetJobApplicationsJobPostIdGetRequestOpts(requestParameters: ApiApplicationGetJobApplicationsJobPostIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobPostId'] == null) {
            throw new runtime.RequiredError(
                'jobPostId',
                'Required parameter "jobPostId" was null or undefined when calling apiApplicationGetJobApplicationsJobPostIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Application/GetJobApplications/{jobPostId}`;
        urlPath = urlPath.replace(`{${"jobPostId"}}`, encodeURIComponent(String(requestParameters['jobPostId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiApplicationGetJobApplicationsJobPostIdGetRaw(requestParameters: ApiApplicationGetJobApplicationsJobPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplicationRecordListRequestResponse>> {
        const requestOptions = await this.apiApplicationGetJobApplicationsJobPostIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationRecordListRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiApplicationGetJobApplicationsJobPostIdGet(requestParameters: ApiApplicationGetJobApplicationsJobPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplicationRecordListRequestResponse> {
        const response = await this.apiApplicationGetJobApplicationsJobPostIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiApplicationGetMyApplicationsGet without sending the request
     */
    async apiApplicationGetMyApplicationsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Application/GetMyApplications`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiApplicationGetMyApplicationsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplicationRecordListRequestResponse>> {
        const requestOptions = await this.apiApplicationGetMyApplicationsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationRecordListRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiApplicationGetMyApplicationsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplicationRecordListRequestResponse> {
        const response = await this.apiApplicationGetMyApplicationsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiApplicationUpdateStatusPut without sending the request
     */
    async apiApplicationUpdateStatusPutRequestOpts(requestParameters: ApiApplicationUpdateStatusPutRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Application/UpdateStatus`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ApplicationUpdateRecordToJSON(requestParameters['applicationUpdateRecord']),
        };
    }

    /**
     */
    async apiApplicationUpdateStatusPutRaw(requestParameters: ApiApplicationUpdateStatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiApplicationUpdateStatusPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiApplicationUpdateStatusPut(requestParameters: ApiApplicationUpdateStatusPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiApplicationUpdateStatusPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
