/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddMemberRequest,
  CompanyMemberRecordListRequestResponse,
  RequestResponse,
  UpdateMemberRoleRequest,
} from '../models/index';
import {
    AddMemberRequestFromJSON,
    AddMemberRequestToJSON,
    CompanyMemberRecordListRequestResponseFromJSON,
    CompanyMemberRecordListRequestResponseToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
    UpdateMemberRoleRequestFromJSON,
    UpdateMemberRoleRequestToJSON,
} from '../models/index';

export interface ApiCompanyMemberAddMemberPostRequest {
    addMemberRequest?: AddMemberRequest;
}

export interface ApiCompanyMemberRemoveMemberUserIdDeleteRequest {
    userId: string;
}

export interface ApiCompanyMemberUpdateMemberRolePutRequest {
    updateMemberRoleRequest?: UpdateMemberRoleRequest;
}

/**
 * 
 */
export class CompanyMemberApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiCompanyMemberAddMemberPost without sending the request
     */
    async apiCompanyMemberAddMemberPostRequestOpts(requestParameters: ApiCompanyMemberAddMemberPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CompanyMember/AddMember`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddMemberRequestToJSON(requestParameters['addMemberRequest']),
        };
    }

    /**
     */
    async apiCompanyMemberAddMemberPostRaw(requestParameters: ApiCompanyMemberAddMemberPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiCompanyMemberAddMemberPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCompanyMemberAddMemberPost(requestParameters: ApiCompanyMemberAddMemberPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCompanyMemberAddMemberPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCompanyMemberGetMembersGet without sending the request
     */
    async apiCompanyMemberGetMembersGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CompanyMember/GetMembers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiCompanyMemberGetMembersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompanyMemberRecordListRequestResponse>> {
        const requestOptions = await this.apiCompanyMemberGetMembersGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompanyMemberRecordListRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCompanyMemberGetMembersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompanyMemberRecordListRequestResponse> {
        const response = await this.apiCompanyMemberGetMembersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCompanyMemberRemoveMemberUserIdDelete without sending the request
     */
    async apiCompanyMemberRemoveMemberUserIdDeleteRequestOpts(requestParameters: ApiCompanyMemberRemoveMemberUserIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiCompanyMemberRemoveMemberUserIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CompanyMember/RemoveMember/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiCompanyMemberRemoveMemberUserIdDeleteRaw(requestParameters: ApiCompanyMemberRemoveMemberUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiCompanyMemberRemoveMemberUserIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCompanyMemberRemoveMemberUserIdDelete(requestParameters: ApiCompanyMemberRemoveMemberUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCompanyMemberRemoveMemberUserIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCompanyMemberUpdateMemberRolePut without sending the request
     */
    async apiCompanyMemberUpdateMemberRolePutRequestOpts(requestParameters: ApiCompanyMemberUpdateMemberRolePutRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CompanyMember/UpdateMemberRole`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMemberRoleRequestToJSON(requestParameters['updateMemberRoleRequest']),
        };
    }

    /**
     */
    async apiCompanyMemberUpdateMemberRolePutRaw(requestParameters: ApiCompanyMemberUpdateMemberRolePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiCompanyMemberUpdateMemberRolePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCompanyMemberUpdateMemberRolePut(requestParameters: ApiCompanyMemberUpdateMemberRolePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCompanyMemberUpdateMemberRolePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
