/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CompanyAddRecord,
  CompanyRecordRequestResponse,
  CompanyUpdateRecord,
  RequestResponse,
} from '../models/index';
import {
    CompanyAddRecordFromJSON,
    CompanyAddRecordToJSON,
    CompanyRecordRequestResponseFromJSON,
    CompanyRecordRequestResponseToJSON,
    CompanyUpdateRecordFromJSON,
    CompanyUpdateRecordToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models/index';

export interface ApiCompanyAddPostRequest {
    companyAddRecord?: CompanyAddRecord;
}

export interface ApiCompanyDeleteIdDeleteRequest {
    id: string;
}

export interface ApiCompanyGetByIdIdGetRequest {
    id: string;
}

export interface ApiCompanyUpdatePutRequest {
    companyUpdateRecord?: CompanyUpdateRecord;
}

/**
 * 
 */
export class CompanyApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiCompanyAddPost without sending the request
     */
    async apiCompanyAddPostRequestOpts(requestParameters: ApiCompanyAddPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Company/Add`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CompanyAddRecordToJSON(requestParameters['companyAddRecord']),
        };
    }

    /**
     */
    async apiCompanyAddPostRaw(requestParameters: ApiCompanyAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiCompanyAddPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCompanyAddPost(requestParameters: ApiCompanyAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCompanyAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCompanyDeleteIdDelete without sending the request
     */
    async apiCompanyDeleteIdDeleteRequestOpts(requestParameters: ApiCompanyDeleteIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCompanyDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Company/Delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiCompanyDeleteIdDeleteRaw(requestParameters: ApiCompanyDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiCompanyDeleteIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCompanyDeleteIdDelete(requestParameters: ApiCompanyDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCompanyDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCompanyGetByIdIdGet without sending the request
     */
    async apiCompanyGetByIdIdGetRequestOpts(requestParameters: ApiCompanyGetByIdIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCompanyGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Company/GetById/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiCompanyGetByIdIdGetRaw(requestParameters: ApiCompanyGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompanyRecordRequestResponse>> {
        const requestOptions = await this.apiCompanyGetByIdIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompanyRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCompanyGetByIdIdGet(requestParameters: ApiCompanyGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompanyRecordRequestResponse> {
        const response = await this.apiCompanyGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCompanyGetMyCompanyGet without sending the request
     */
    async apiCompanyGetMyCompanyGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Company/GetMyCompany`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiCompanyGetMyCompanyGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompanyRecordRequestResponse>> {
        const requestOptions = await this.apiCompanyGetMyCompanyGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompanyRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCompanyGetMyCompanyGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompanyRecordRequestResponse> {
        const response = await this.apiCompanyGetMyCompanyGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCompanyUpdatePut without sending the request
     */
    async apiCompanyUpdatePutRequestOpts(requestParameters: ApiCompanyUpdatePutRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Company/Update`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CompanyUpdateRecordToJSON(requestParameters['companyUpdateRecord']),
        };
    }

    /**
     */
    async apiCompanyUpdatePutRaw(requestParameters: ApiCompanyUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiCompanyUpdatePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCompanyUpdatePut(requestParameters: ApiCompanyUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCompanyUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
