/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JobPostAddRecord,
  JobPostRecordListRequestResponse,
  JobPostRecordRequestResponse,
  JobPostUpdateRecord,
  RequestResponse,
} from '../models/index';
import {
    JobPostAddRecordFromJSON,
    JobPostAddRecordToJSON,
    JobPostRecordListRequestResponseFromJSON,
    JobPostRecordListRequestResponseToJSON,
    JobPostRecordRequestResponseFromJSON,
    JobPostRecordRequestResponseToJSON,
    JobPostUpdateRecordFromJSON,
    JobPostUpdateRecordToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models/index';

export interface ApiJobPostAddPostRequest {
    jobPostAddRecord?: JobPostAddRecord;
}

export interface ApiJobPostDeleteIdDeleteRequest {
    id: string;
}

export interface ApiJobPostGetByIdIdGetRequest {
    id: string;
}

export interface ApiJobPostUpdatePutRequest {
    jobPostUpdateRecord?: JobPostUpdateRecord;
}

/**
 * 
 */
export class JobPostApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiJobPostAddPost without sending the request
     */
    async apiJobPostAddPostRequestOpts(requestParameters: ApiJobPostAddPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/JobPost/Add`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JobPostAddRecordToJSON(requestParameters['jobPostAddRecord']),
        };
    }

    /**
     */
    async apiJobPostAddPostRaw(requestParameters: ApiJobPostAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiJobPostAddPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiJobPostAddPost(requestParameters: ApiJobPostAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiJobPostAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiJobPostDeleteIdDelete without sending the request
     */
    async apiJobPostDeleteIdDeleteRequestOpts(requestParameters: ApiJobPostDeleteIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiJobPostDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/JobPost/Delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiJobPostDeleteIdDeleteRaw(requestParameters: ApiJobPostDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiJobPostDeleteIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiJobPostDeleteIdDelete(requestParameters: ApiJobPostDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiJobPostDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiJobPostGetAllAllGet without sending the request
     */
    async apiJobPostGetAllAllGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/JobPost/GetAll/all`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiJobPostGetAllAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobPostRecordListRequestResponse>> {
        const requestOptions = await this.apiJobPostGetAllAllGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobPostRecordListRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiJobPostGetAllAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobPostRecordListRequestResponse> {
        const response = await this.apiJobPostGetAllAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiJobPostGetByIdIdGet without sending the request
     */
    async apiJobPostGetByIdIdGetRequestOpts(requestParameters: ApiJobPostGetByIdIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiJobPostGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/JobPost/GetById/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiJobPostGetByIdIdGetRaw(requestParameters: ApiJobPostGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobPostRecordRequestResponse>> {
        const requestOptions = await this.apiJobPostGetByIdIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobPostRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiJobPostGetByIdIdGet(requestParameters: ApiJobPostGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobPostRecordRequestResponse> {
        const response = await this.apiJobPostGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiJobPostGetMyCompanyJobsGet without sending the request
     */
    async apiJobPostGetMyCompanyJobsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/JobPost/GetMyCompanyJobs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiJobPostGetMyCompanyJobsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobPostRecordListRequestResponse>> {
        const requestOptions = await this.apiJobPostGetMyCompanyJobsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobPostRecordListRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiJobPostGetMyCompanyJobsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobPostRecordListRequestResponse> {
        const response = await this.apiJobPostGetMyCompanyJobsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiJobPostUpdatePut without sending the request
     */
    async apiJobPostUpdatePutRequestOpts(requestParameters: ApiJobPostUpdatePutRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/JobPost/Update`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: JobPostUpdateRecordToJSON(requestParameters['jobPostUpdateRecord']),
        };
    }

    /**
     */
    async apiJobPostUpdatePutRaw(requestParameters: ApiJobPostUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiJobPostUpdatePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiJobPostUpdatePut(requestParameters: ApiJobPostUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiJobPostUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
