/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RequestResponse,
  UserProfileRecordRequestResponse,
  UserProfileUpdateRecord,
} from '../models/index';
import {
    RequestResponseFromJSON,
    RequestResponseToJSON,
    UserProfileRecordRequestResponseFromJSON,
    UserProfileRecordRequestResponseToJSON,
    UserProfileUpdateRecordFromJSON,
    UserProfileUpdateRecordToJSON,
} from '../models/index';

export interface ApiUserProfileGetProfileUserIdGetRequest {
    userId: string;
}

export interface ApiUserProfileUpdateProfilePutRequest {
    userProfileUpdateRecord?: UserProfileUpdateRecord;
}

/**
 * 
 */
export class UserProfileApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiUserProfileGetMyProfileGet without sending the request
     */
    async apiUserProfileGetMyProfileGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/UserProfile/GetMyProfile`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiUserProfileGetMyProfileGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileRecordRequestResponse>> {
        const requestOptions = await this.apiUserProfileGetMyProfileGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProfileRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiUserProfileGetMyProfileGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileRecordRequestResponse> {
        const response = await this.apiUserProfileGetMyProfileGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiUserProfileGetProfileUserIdGet without sending the request
     */
    async apiUserProfileGetProfileUserIdGetRequestOpts(requestParameters: ApiUserProfileGetProfileUserIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiUserProfileGetProfileUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/UserProfile/GetProfile/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiUserProfileGetProfileUserIdGetRaw(requestParameters: ApiUserProfileGetProfileUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileRecordRequestResponse>> {
        const requestOptions = await this.apiUserProfileGetProfileUserIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProfileRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiUserProfileGetProfileUserIdGet(requestParameters: ApiUserProfileGetProfileUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileRecordRequestResponse> {
        const response = await this.apiUserProfileGetProfileUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiUserProfileUpdateProfilePut without sending the request
     */
    async apiUserProfileUpdateProfilePutRequestOpts(requestParameters: ApiUserProfileUpdateProfilePutRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/UserProfile/UpdateProfile`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserProfileUpdateRecordToJSON(requestParameters['userProfileUpdateRecord']),
        };
    }

    /**
     */
    async apiUserProfileUpdateProfilePutRaw(requestParameters: ApiUserProfileUpdateProfilePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiUserProfileUpdateProfilePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiUserProfileUpdateProfilePut(requestParameters: ApiUserProfileUpdateProfilePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiUserProfileUpdateProfilePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
